SET XACT_ABORT ON;
SET NOCOUNT ON;
BEGIN TRY
    BEGIN TRAN;
    ALTER PARTITION SCHEME [{PartitionScheme}] NEXT USED [{FilegroupName}];
    ALTER PARTITION FUNCTION [{PartitionFunction}]() SPLIT RANGE ({BoundaryLiteral});
    COMMIT TRAN;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRAN;
    DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
    RAISERROR (''分区拆分失败: %s'', 16, 1, @ErrorMessage);
END CATCH;
